# Generated by Django 2.2 on 2019-04-25 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='name')),
                ('code', models.CharField(max_length=2, verbose_name='code')),
            ],
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, max_length=250)),
                ('url', models.SlugField(allow_unicode=True, blank=True)),
                ('title_image', models.ImageField(blank=True, upload_to='mod/title_image/')),
                ('rating', models.SmallIntegerField(blank=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('order_index', models.IntegerField(blank=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('compatibility_mod', models.ManyToManyField(blank=True, related_name='mod_compatibilities', to='mods.Mod')),
                ('incompatibility_mod', models.ManyToManyField(blank=True, related_name='mod_incompatibilities', to='mods.Mod')),
            ],
            options={
                'default_related_name': 'mods',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ModImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mod/images')),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_images', to='mods.Mod')),
            ],
            options={
                'ordering': ('mod',),
            },
        ),
        migrations.CreateModel(
            name='ModFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mod/files')),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_files', to='mods.Mod')),
            ],
            options={
                'ordering': ('mod',),
            },
        ),
        migrations.AddField(
            model_name='mod',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='mods', to='mods.Tag'),
        ),
    ]
